// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: src/main/proto/Simple.Proto

package com.keyhunter.test.serialization.proto;

public final class Simple {
  private Simple() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface SimpleObjectOrBuilder extends
      // @@protoc_insertion_point(interface_extends:SimpleObject)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>optional string name = 1;</code>
     */
    boolean hasName();
    /**
     * <code>optional string name = 1;</code>
     */
    java.lang.String getName();
    /**
     * <code>optional string name = 1;</code>
     */
    com.google.protobuf.ByteString
        getNameBytes();

    /**
     * <code>optional string value = 2;</code>
     */
    boolean hasValue();
    /**
     * <code>optional string value = 2;</code>
     */
    java.lang.String getValue();
    /**
     * <code>optional string value = 2;</code>
     */
    com.google.protobuf.ByteString
        getValueBytes();

    /**
     * <code>optional int32 age = 3;</code>
     */
    boolean hasAge();
    /**
     * <code>optional int32 age = 3;</code>
     */
    int getAge();

    /**
     * <code>optional string mail = 4;</code>
     */
    boolean hasMail();
    /**
     * <code>optional string mail = 4;</code>
     */
    java.lang.String getMail();
    /**
     * <code>optional string mail = 4;</code>
     */
    com.google.protobuf.ByteString
        getMailBytes();

    /**
     * <code>optional double score = 5;</code>
     */
    boolean hasScore();
    /**
     * <code>optional double score = 5;</code>
     */
    double getScore();

    /**
     * <code>optional double height = 6;</code>
     */
    boolean hasHeight();
    /**
     * <code>optional double height = 6;</code>
     */
    double getHeight();

    /**
     * <code>optional double weight = 7;</code>
     */
    boolean hasWeight();
    /**
     * <code>optional double weight = 7;</code>
     */
    double getWeight();

    /**
     * <code>optional string school = 8;</code>
     */
    boolean hasSchool();
    /**
     * <code>optional string school = 8;</code>
     */
    java.lang.String getSchool();
    /**
     * <code>optional string school = 8;</code>
     */
    com.google.protobuf.ByteString
        getSchoolBytes();

    /**
     * <code>optional string teacher = 9;</code>
     */
    boolean hasTeacher();
    /**
     * <code>optional string teacher = 9;</code>
     */
    java.lang.String getTeacher();
    /**
     * <code>optional string teacher = 9;</code>
     */
    com.google.protobuf.ByteString
        getTeacherBytes();

    /**
     * <code>repeated string parents = 10;</code>
     */
    java.util.List<java.lang.String>
        getParentsList();
    /**
     * <code>repeated string parents = 10;</code>
     */
    int getParentsCount();
    /**
     * <code>repeated string parents = 10;</code>
     */
    java.lang.String getParents(int index);
    /**
     * <code>repeated string parents = 10;</code>
     */
    com.google.protobuf.ByteString
        getParentsBytes(int index);

    /**
     * <code>optional string desc = 11;</code>
     */
    boolean hasDesc();
    /**
     * <code>optional string desc = 11;</code>
     */
    java.lang.String getDesc();
    /**
     * <code>optional string desc = 11;</code>
     */
    com.google.protobuf.ByteString
        getDescBytes();
  }
  /**
   * Protobuf type {@code SimpleObject}
   */
  public  static final class SimpleObject extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:SimpleObject)
      SimpleObjectOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use SimpleObject.newBuilder() to construct.
    private SimpleObject(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private SimpleObject() {
      name_ = "";
      value_ = "";
      age_ = 0;
      mail_ = "";
      score_ = 0D;
      height_ = 0D;
      weight_ = 0D;
      school_ = "";
      teacher_ = "";
      parents_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      desc_ = "";
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private SimpleObject(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000001;
              name_ = bs;
              break;
            }
            case 18: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000002;
              value_ = bs;
              break;
            }
            case 24: {
              bitField0_ |= 0x00000004;
              age_ = input.readInt32();
              break;
            }
            case 34: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000008;
              mail_ = bs;
              break;
            }
            case 41: {
              bitField0_ |= 0x00000010;
              score_ = input.readDouble();
              break;
            }
            case 49: {
              bitField0_ |= 0x00000020;
              height_ = input.readDouble();
              break;
            }
            case 57: {
              bitField0_ |= 0x00000040;
              weight_ = input.readDouble();
              break;
            }
            case 66: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000080;
              school_ = bs;
              break;
            }
            case 74: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000100;
              teacher_ = bs;
              break;
            }
            case 82: {
              com.google.protobuf.ByteString bs = input.readBytes();
              if (!((mutable_bitField0_ & 0x00000200) == 0x00000200)) {
                parents_ = new com.google.protobuf.LazyStringArrayList();
                mutable_bitField0_ |= 0x00000200;
              }
              parents_.add(bs);
              break;
            }
            case 90: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000200;
              desc_ = bs;
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000200) == 0x00000200)) {
          parents_ = parents_.getUnmodifiableView();
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.keyhunter.test.serialization.proto.Simple.internal_static_SimpleObject_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.keyhunter.test.serialization.proto.Simple.internal_static_SimpleObject_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.keyhunter.test.serialization.proto.Simple.SimpleObject.class, com.keyhunter.test.serialization.proto.Simple.SimpleObject.Builder.class);
    }

    private int bitField0_;
    public static final int NAME_FIELD_NUMBER = 1;
    private volatile java.lang.Object name_;
    /**
     * <code>optional string name = 1;</code>
     */
    public boolean hasName() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>optional string name = 1;</code>
     */
    public java.lang.String getName() {
      java.lang.Object ref = name_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          name_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string name = 1;</code>
     */
    public com.google.protobuf.ByteString
        getNameBytes() {
      java.lang.Object ref = name_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        name_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int VALUE_FIELD_NUMBER = 2;
    private volatile java.lang.Object value_;
    /**
     * <code>optional string value = 2;</code>
     */
    public boolean hasValue() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>optional string value = 2;</code>
     */
    public java.lang.String getValue() {
      java.lang.Object ref = value_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          value_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string value = 2;</code>
     */
    public com.google.protobuf.ByteString
        getValueBytes() {
      java.lang.Object ref = value_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        value_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int AGE_FIELD_NUMBER = 3;
    private int age_;
    /**
     * <code>optional int32 age = 3;</code>
     */
    public boolean hasAge() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>optional int32 age = 3;</code>
     */
    public int getAge() {
      return age_;
    }

    public static final int MAIL_FIELD_NUMBER = 4;
    private volatile java.lang.Object mail_;
    /**
     * <code>optional string mail = 4;</code>
     */
    public boolean hasMail() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    /**
     * <code>optional string mail = 4;</code>
     */
    public java.lang.String getMail() {
      java.lang.Object ref = mail_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          mail_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string mail = 4;</code>
     */
    public com.google.protobuf.ByteString
        getMailBytes() {
      java.lang.Object ref = mail_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        mail_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int SCORE_FIELD_NUMBER = 5;
    private double score_;
    /**
     * <code>optional double score = 5;</code>
     */
    public boolean hasScore() {
      return ((bitField0_ & 0x00000010) == 0x00000010);
    }
    /**
     * <code>optional double score = 5;</code>
     */
    public double getScore() {
      return score_;
    }

    public static final int HEIGHT_FIELD_NUMBER = 6;
    private double height_;
    /**
     * <code>optional double height = 6;</code>
     */
    public boolean hasHeight() {
      return ((bitField0_ & 0x00000020) == 0x00000020);
    }
    /**
     * <code>optional double height = 6;</code>
     */
    public double getHeight() {
      return height_;
    }

    public static final int WEIGHT_FIELD_NUMBER = 7;
    private double weight_;
    /**
     * <code>optional double weight = 7;</code>
     */
    public boolean hasWeight() {
      return ((bitField0_ & 0x00000040) == 0x00000040);
    }
    /**
     * <code>optional double weight = 7;</code>
     */
    public double getWeight() {
      return weight_;
    }

    public static final int SCHOOL_FIELD_NUMBER = 8;
    private volatile java.lang.Object school_;
    /**
     * <code>optional string school = 8;</code>
     */
    public boolean hasSchool() {
      return ((bitField0_ & 0x00000080) == 0x00000080);
    }
    /**
     * <code>optional string school = 8;</code>
     */
    public java.lang.String getSchool() {
      java.lang.Object ref = school_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          school_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string school = 8;</code>
     */
    public com.google.protobuf.ByteString
        getSchoolBytes() {
      java.lang.Object ref = school_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        school_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int TEACHER_FIELD_NUMBER = 9;
    private volatile java.lang.Object teacher_;
    /**
     * <code>optional string teacher = 9;</code>
     */
    public boolean hasTeacher() {
      return ((bitField0_ & 0x00000100) == 0x00000100);
    }
    /**
     * <code>optional string teacher = 9;</code>
     */
    public java.lang.String getTeacher() {
      java.lang.Object ref = teacher_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          teacher_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string teacher = 9;</code>
     */
    public com.google.protobuf.ByteString
        getTeacherBytes() {
      java.lang.Object ref = teacher_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        teacher_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int PARENTS_FIELD_NUMBER = 10;
    private com.google.protobuf.LazyStringList parents_;
    /**
     * <code>repeated string parents = 10;</code>
     */
    public com.google.protobuf.ProtocolStringList
        getParentsList() {
      return parents_;
    }
    /**
     * <code>repeated string parents = 10;</code>
     */
    public int getParentsCount() {
      return parents_.size();
    }
    /**
     * <code>repeated string parents = 10;</code>
     */
    public java.lang.String getParents(int index) {
      return parents_.get(index);
    }
    /**
     * <code>repeated string parents = 10;</code>
     */
    public com.google.protobuf.ByteString
        getParentsBytes(int index) {
      return parents_.getByteString(index);
    }

    public static final int DESC_FIELD_NUMBER = 11;
    private volatile java.lang.Object desc_;
    /**
     * <code>optional string desc = 11;</code>
     */
    public boolean hasDesc() {
      return ((bitField0_ & 0x00000200) == 0x00000200);
    }
    /**
     * <code>optional string desc = 11;</code>
     */
    public java.lang.String getDesc() {
      java.lang.Object ref = desc_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          desc_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string desc = 11;</code>
     */
    public com.google.protobuf.ByteString
        getDescBytes() {
      java.lang.Object ref = desc_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        desc_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, name_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, value_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeInt32(3, age_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 4, mail_);
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        output.writeDouble(5, score_);
      }
      if (((bitField0_ & 0x00000020) == 0x00000020)) {
        output.writeDouble(6, height_);
      }
      if (((bitField0_ & 0x00000040) == 0x00000040)) {
        output.writeDouble(7, weight_);
      }
      if (((bitField0_ & 0x00000080) == 0x00000080)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 8, school_);
      }
      if (((bitField0_ & 0x00000100) == 0x00000100)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 9, teacher_);
      }
      for (int i = 0; i < parents_.size(); i++) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 10, parents_.getRaw(i));
      }
      if (((bitField0_ & 0x00000200) == 0x00000200)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 11, desc_);
      }
      unknownFields.writeTo(output);
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, name_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, value_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(3, age_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, mail_);
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        size += com.google.protobuf.CodedOutputStream
          .computeDoubleSize(5, score_);
      }
      if (((bitField0_ & 0x00000020) == 0x00000020)) {
        size += com.google.protobuf.CodedOutputStream
          .computeDoubleSize(6, height_);
      }
      if (((bitField0_ & 0x00000040) == 0x00000040)) {
        size += com.google.protobuf.CodedOutputStream
          .computeDoubleSize(7, weight_);
      }
      if (((bitField0_ & 0x00000080) == 0x00000080)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(8, school_);
      }
      if (((bitField0_ & 0x00000100) == 0x00000100)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(9, teacher_);
      }
      {
        int dataSize = 0;
        for (int i = 0; i < parents_.size(); i++) {
          dataSize += computeStringSizeNoTag(parents_.getRaw(i));
        }
        size += dataSize;
        size += 1 * getParentsList().size();
      }
      if (((bitField0_ & 0x00000200) == 0x00000200)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(11, desc_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.keyhunter.test.serialization.proto.Simple.SimpleObject)) {
        return super.equals(obj);
      }
      com.keyhunter.test.serialization.proto.Simple.SimpleObject other = (com.keyhunter.test.serialization.proto.Simple.SimpleObject) obj;

      boolean result = true;
      result = result && (hasName() == other.hasName());
      if (hasName()) {
        result = result && getName()
            .equals(other.getName());
      }
      result = result && (hasValue() == other.hasValue());
      if (hasValue()) {
        result = result && getValue()
            .equals(other.getValue());
      }
      result = result && (hasAge() == other.hasAge());
      if (hasAge()) {
        result = result && (getAge()
            == other.getAge());
      }
      result = result && (hasMail() == other.hasMail());
      if (hasMail()) {
        result = result && getMail()
            .equals(other.getMail());
      }
      result = result && (hasScore() == other.hasScore());
      if (hasScore()) {
        result = result && (
            java.lang.Double.doubleToLongBits(getScore())
            == java.lang.Double.doubleToLongBits(
                other.getScore()));
      }
      result = result && (hasHeight() == other.hasHeight());
      if (hasHeight()) {
        result = result && (
            java.lang.Double.doubleToLongBits(getHeight())
            == java.lang.Double.doubleToLongBits(
                other.getHeight()));
      }
      result = result && (hasWeight() == other.hasWeight());
      if (hasWeight()) {
        result = result && (
            java.lang.Double.doubleToLongBits(getWeight())
            == java.lang.Double.doubleToLongBits(
                other.getWeight()));
      }
      result = result && (hasSchool() == other.hasSchool());
      if (hasSchool()) {
        result = result && getSchool()
            .equals(other.getSchool());
      }
      result = result && (hasTeacher() == other.hasTeacher());
      if (hasTeacher()) {
        result = result && getTeacher()
            .equals(other.getTeacher());
      }
      result = result && getParentsList()
          .equals(other.getParentsList());
      result = result && (hasDesc() == other.hasDesc());
      if (hasDesc()) {
        result = result && getDesc()
            .equals(other.getDesc());
      }
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (hasName()) {
        hash = (37 * hash) + NAME_FIELD_NUMBER;
        hash = (53 * hash) + getName().hashCode();
      }
      if (hasValue()) {
        hash = (37 * hash) + VALUE_FIELD_NUMBER;
        hash = (53 * hash) + getValue().hashCode();
      }
      if (hasAge()) {
        hash = (37 * hash) + AGE_FIELD_NUMBER;
        hash = (53 * hash) + getAge();
      }
      if (hasMail()) {
        hash = (37 * hash) + MAIL_FIELD_NUMBER;
        hash = (53 * hash) + getMail().hashCode();
      }
      if (hasScore()) {
        hash = (37 * hash) + SCORE_FIELD_NUMBER;
        hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
            java.lang.Double.doubleToLongBits(getScore()));
      }
      if (hasHeight()) {
        hash = (37 * hash) + HEIGHT_FIELD_NUMBER;
        hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
            java.lang.Double.doubleToLongBits(getHeight()));
      }
      if (hasWeight()) {
        hash = (37 * hash) + WEIGHT_FIELD_NUMBER;
        hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
            java.lang.Double.doubleToLongBits(getWeight()));
      }
      if (hasSchool()) {
        hash = (37 * hash) + SCHOOL_FIELD_NUMBER;
        hash = (53 * hash) + getSchool().hashCode();
      }
      if (hasTeacher()) {
        hash = (37 * hash) + TEACHER_FIELD_NUMBER;
        hash = (53 * hash) + getTeacher().hashCode();
      }
      if (getParentsCount() > 0) {
        hash = (37 * hash) + PARENTS_FIELD_NUMBER;
        hash = (53 * hash) + getParentsList().hashCode();
      }
      if (hasDesc()) {
        hash = (37 * hash) + DESC_FIELD_NUMBER;
        hash = (53 * hash) + getDesc().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.keyhunter.test.serialization.proto.Simple.SimpleObject parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.keyhunter.test.serialization.proto.Simple.SimpleObject parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.keyhunter.test.serialization.proto.Simple.SimpleObject parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.keyhunter.test.serialization.proto.Simple.SimpleObject parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.keyhunter.test.serialization.proto.Simple.SimpleObject parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.keyhunter.test.serialization.proto.Simple.SimpleObject parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.keyhunter.test.serialization.proto.Simple.SimpleObject parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.keyhunter.test.serialization.proto.Simple.SimpleObject parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.keyhunter.test.serialization.proto.Simple.SimpleObject parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.keyhunter.test.serialization.proto.Simple.SimpleObject parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.keyhunter.test.serialization.proto.Simple.SimpleObject parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.keyhunter.test.serialization.proto.Simple.SimpleObject parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.keyhunter.test.serialization.proto.Simple.SimpleObject prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code SimpleObject}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:SimpleObject)
        com.keyhunter.test.serialization.proto.Simple.SimpleObjectOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.keyhunter.test.serialization.proto.Simple.internal_static_SimpleObject_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.keyhunter.test.serialization.proto.Simple.internal_static_SimpleObject_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.keyhunter.test.serialization.proto.Simple.SimpleObject.class, com.keyhunter.test.serialization.proto.Simple.SimpleObject.Builder.class);
      }

      // Construct using com.keyhunter.test.serialization.proto.Simple.SimpleObject.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        name_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        value_ = "";
        bitField0_ = (bitField0_ & ~0x00000002);
        age_ = 0;
        bitField0_ = (bitField0_ & ~0x00000004);
        mail_ = "";
        bitField0_ = (bitField0_ & ~0x00000008);
        score_ = 0D;
        bitField0_ = (bitField0_ & ~0x00000010);
        height_ = 0D;
        bitField0_ = (bitField0_ & ~0x00000020);
        weight_ = 0D;
        bitField0_ = (bitField0_ & ~0x00000040);
        school_ = "";
        bitField0_ = (bitField0_ & ~0x00000080);
        teacher_ = "";
        bitField0_ = (bitField0_ & ~0x00000100);
        parents_ = com.google.protobuf.LazyStringArrayList.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000200);
        desc_ = "";
        bitField0_ = (bitField0_ & ~0x00000400);
        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.keyhunter.test.serialization.proto.Simple.internal_static_SimpleObject_descriptor;
      }

      public com.keyhunter.test.serialization.proto.Simple.SimpleObject getDefaultInstanceForType() {
        return com.keyhunter.test.serialization.proto.Simple.SimpleObject.getDefaultInstance();
      }

      public com.keyhunter.test.serialization.proto.Simple.SimpleObject build() {
        com.keyhunter.test.serialization.proto.Simple.SimpleObject result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.keyhunter.test.serialization.proto.Simple.SimpleObject buildPartial() {
        com.keyhunter.test.serialization.proto.Simple.SimpleObject result = new com.keyhunter.test.serialization.proto.Simple.SimpleObject(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.name_ = name_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.value_ = value_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.age_ = age_;
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000008;
        }
        result.mail_ = mail_;
        if (((from_bitField0_ & 0x00000010) == 0x00000010)) {
          to_bitField0_ |= 0x00000010;
        }
        result.score_ = score_;
        if (((from_bitField0_ & 0x00000020) == 0x00000020)) {
          to_bitField0_ |= 0x00000020;
        }
        result.height_ = height_;
        if (((from_bitField0_ & 0x00000040) == 0x00000040)) {
          to_bitField0_ |= 0x00000040;
        }
        result.weight_ = weight_;
        if (((from_bitField0_ & 0x00000080) == 0x00000080)) {
          to_bitField0_ |= 0x00000080;
        }
        result.school_ = school_;
        if (((from_bitField0_ & 0x00000100) == 0x00000100)) {
          to_bitField0_ |= 0x00000100;
        }
        result.teacher_ = teacher_;
        if (((bitField0_ & 0x00000200) == 0x00000200)) {
          parents_ = parents_.getUnmodifiableView();
          bitField0_ = (bitField0_ & ~0x00000200);
        }
        result.parents_ = parents_;
        if (((from_bitField0_ & 0x00000400) == 0x00000400)) {
          to_bitField0_ |= 0x00000200;
        }
        result.desc_ = desc_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.keyhunter.test.serialization.proto.Simple.SimpleObject) {
          return mergeFrom((com.keyhunter.test.serialization.proto.Simple.SimpleObject)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.keyhunter.test.serialization.proto.Simple.SimpleObject other) {
        if (other == com.keyhunter.test.serialization.proto.Simple.SimpleObject.getDefaultInstance()) return this;
        if (other.hasName()) {
          bitField0_ |= 0x00000001;
          name_ = other.name_;
          onChanged();
        }
        if (other.hasValue()) {
          bitField0_ |= 0x00000002;
          value_ = other.value_;
          onChanged();
        }
        if (other.hasAge()) {
          setAge(other.getAge());
        }
        if (other.hasMail()) {
          bitField0_ |= 0x00000008;
          mail_ = other.mail_;
          onChanged();
        }
        if (other.hasScore()) {
          setScore(other.getScore());
        }
        if (other.hasHeight()) {
          setHeight(other.getHeight());
        }
        if (other.hasWeight()) {
          setWeight(other.getWeight());
        }
        if (other.hasSchool()) {
          bitField0_ |= 0x00000080;
          school_ = other.school_;
          onChanged();
        }
        if (other.hasTeacher()) {
          bitField0_ |= 0x00000100;
          teacher_ = other.teacher_;
          onChanged();
        }
        if (!other.parents_.isEmpty()) {
          if (parents_.isEmpty()) {
            parents_ = other.parents_;
            bitField0_ = (bitField0_ & ~0x00000200);
          } else {
            ensureParentsIsMutable();
            parents_.addAll(other.parents_);
          }
          onChanged();
        }
        if (other.hasDesc()) {
          bitField0_ |= 0x00000400;
          desc_ = other.desc_;
          onChanged();
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.keyhunter.test.serialization.proto.Simple.SimpleObject parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.keyhunter.test.serialization.proto.Simple.SimpleObject) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.lang.Object name_ = "";
      /**
       * <code>optional string name = 1;</code>
       */
      public boolean hasName() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>optional string name = 1;</code>
       */
      public java.lang.String getName() {
        java.lang.Object ref = name_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            name_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string name = 1;</code>
       */
      public com.google.protobuf.ByteString
          getNameBytes() {
        java.lang.Object ref = name_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          name_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string name = 1;</code>
       */
      public Builder setName(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        name_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string name = 1;</code>
       */
      public Builder clearName() {
        bitField0_ = (bitField0_ & ~0x00000001);
        name_ = getDefaultInstance().getName();
        onChanged();
        return this;
      }
      /**
       * <code>optional string name = 1;</code>
       */
      public Builder setNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        name_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object value_ = "";
      /**
       * <code>optional string value = 2;</code>
       */
      public boolean hasValue() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>optional string value = 2;</code>
       */
      public java.lang.String getValue() {
        java.lang.Object ref = value_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            value_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string value = 2;</code>
       */
      public com.google.protobuf.ByteString
          getValueBytes() {
        java.lang.Object ref = value_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          value_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string value = 2;</code>
       */
      public Builder setValue(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        value_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string value = 2;</code>
       */
      public Builder clearValue() {
        bitField0_ = (bitField0_ & ~0x00000002);
        value_ = getDefaultInstance().getValue();
        onChanged();
        return this;
      }
      /**
       * <code>optional string value = 2;</code>
       */
      public Builder setValueBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        value_ = value;
        onChanged();
        return this;
      }

      private int age_ ;
      /**
       * <code>optional int32 age = 3;</code>
       */
      public boolean hasAge() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>optional int32 age = 3;</code>
       */
      public int getAge() {
        return age_;
      }
      /**
       * <code>optional int32 age = 3;</code>
       */
      public Builder setAge(int value) {
        bitField0_ |= 0x00000004;
        age_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 age = 3;</code>
       */
      public Builder clearAge() {
        bitField0_ = (bitField0_ & ~0x00000004);
        age_ = 0;
        onChanged();
        return this;
      }

      private java.lang.Object mail_ = "";
      /**
       * <code>optional string mail = 4;</code>
       */
      public boolean hasMail() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      /**
       * <code>optional string mail = 4;</code>
       */
      public java.lang.String getMail() {
        java.lang.Object ref = mail_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            mail_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string mail = 4;</code>
       */
      public com.google.protobuf.ByteString
          getMailBytes() {
        java.lang.Object ref = mail_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          mail_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string mail = 4;</code>
       */
      public Builder setMail(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000008;
        mail_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string mail = 4;</code>
       */
      public Builder clearMail() {
        bitField0_ = (bitField0_ & ~0x00000008);
        mail_ = getDefaultInstance().getMail();
        onChanged();
        return this;
      }
      /**
       * <code>optional string mail = 4;</code>
       */
      public Builder setMailBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000008;
        mail_ = value;
        onChanged();
        return this;
      }

      private double score_ ;
      /**
       * <code>optional double score = 5;</code>
       */
      public boolean hasScore() {
        return ((bitField0_ & 0x00000010) == 0x00000010);
      }
      /**
       * <code>optional double score = 5;</code>
       */
      public double getScore() {
        return score_;
      }
      /**
       * <code>optional double score = 5;</code>
       */
      public Builder setScore(double value) {
        bitField0_ |= 0x00000010;
        score_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional double score = 5;</code>
       */
      public Builder clearScore() {
        bitField0_ = (bitField0_ & ~0x00000010);
        score_ = 0D;
        onChanged();
        return this;
      }

      private double height_ ;
      /**
       * <code>optional double height = 6;</code>
       */
      public boolean hasHeight() {
        return ((bitField0_ & 0x00000020) == 0x00000020);
      }
      /**
       * <code>optional double height = 6;</code>
       */
      public double getHeight() {
        return height_;
      }
      /**
       * <code>optional double height = 6;</code>
       */
      public Builder setHeight(double value) {
        bitField0_ |= 0x00000020;
        height_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional double height = 6;</code>
       */
      public Builder clearHeight() {
        bitField0_ = (bitField0_ & ~0x00000020);
        height_ = 0D;
        onChanged();
        return this;
      }

      private double weight_ ;
      /**
       * <code>optional double weight = 7;</code>
       */
      public boolean hasWeight() {
        return ((bitField0_ & 0x00000040) == 0x00000040);
      }
      /**
       * <code>optional double weight = 7;</code>
       */
      public double getWeight() {
        return weight_;
      }
      /**
       * <code>optional double weight = 7;</code>
       */
      public Builder setWeight(double value) {
        bitField0_ |= 0x00000040;
        weight_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional double weight = 7;</code>
       */
      public Builder clearWeight() {
        bitField0_ = (bitField0_ & ~0x00000040);
        weight_ = 0D;
        onChanged();
        return this;
      }

      private java.lang.Object school_ = "";
      /**
       * <code>optional string school = 8;</code>
       */
      public boolean hasSchool() {
        return ((bitField0_ & 0x00000080) == 0x00000080);
      }
      /**
       * <code>optional string school = 8;</code>
       */
      public java.lang.String getSchool() {
        java.lang.Object ref = school_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            school_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string school = 8;</code>
       */
      public com.google.protobuf.ByteString
          getSchoolBytes() {
        java.lang.Object ref = school_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          school_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string school = 8;</code>
       */
      public Builder setSchool(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000080;
        school_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string school = 8;</code>
       */
      public Builder clearSchool() {
        bitField0_ = (bitField0_ & ~0x00000080);
        school_ = getDefaultInstance().getSchool();
        onChanged();
        return this;
      }
      /**
       * <code>optional string school = 8;</code>
       */
      public Builder setSchoolBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000080;
        school_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object teacher_ = "";
      /**
       * <code>optional string teacher = 9;</code>
       */
      public boolean hasTeacher() {
        return ((bitField0_ & 0x00000100) == 0x00000100);
      }
      /**
       * <code>optional string teacher = 9;</code>
       */
      public java.lang.String getTeacher() {
        java.lang.Object ref = teacher_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            teacher_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string teacher = 9;</code>
       */
      public com.google.protobuf.ByteString
          getTeacherBytes() {
        java.lang.Object ref = teacher_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          teacher_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string teacher = 9;</code>
       */
      public Builder setTeacher(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000100;
        teacher_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string teacher = 9;</code>
       */
      public Builder clearTeacher() {
        bitField0_ = (bitField0_ & ~0x00000100);
        teacher_ = getDefaultInstance().getTeacher();
        onChanged();
        return this;
      }
      /**
       * <code>optional string teacher = 9;</code>
       */
      public Builder setTeacherBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000100;
        teacher_ = value;
        onChanged();
        return this;
      }

      private com.google.protobuf.LazyStringList parents_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      private void ensureParentsIsMutable() {
        if (!((bitField0_ & 0x00000200) == 0x00000200)) {
          parents_ = new com.google.protobuf.LazyStringArrayList(parents_);
          bitField0_ |= 0x00000200;
         }
      }
      /**
       * <code>repeated string parents = 10;</code>
       */
      public com.google.protobuf.ProtocolStringList
          getParentsList() {
        return parents_.getUnmodifiableView();
      }
      /**
       * <code>repeated string parents = 10;</code>
       */
      public int getParentsCount() {
        return parents_.size();
      }
      /**
       * <code>repeated string parents = 10;</code>
       */
      public java.lang.String getParents(int index) {
        return parents_.get(index);
      }
      /**
       * <code>repeated string parents = 10;</code>
       */
      public com.google.protobuf.ByteString
          getParentsBytes(int index) {
        return parents_.getByteString(index);
      }
      /**
       * <code>repeated string parents = 10;</code>
       */
      public Builder setParents(
          int index, java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureParentsIsMutable();
        parents_.set(index, value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string parents = 10;</code>
       */
      public Builder addParents(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureParentsIsMutable();
        parents_.add(value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string parents = 10;</code>
       */
      public Builder addAllParents(
          java.lang.Iterable<java.lang.String> values) {
        ensureParentsIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, parents_);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string parents = 10;</code>
       */
      public Builder clearParents() {
        parents_ = com.google.protobuf.LazyStringArrayList.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000200);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string parents = 10;</code>
       */
      public Builder addParentsBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureParentsIsMutable();
        parents_.add(value);
        onChanged();
        return this;
      }

      private java.lang.Object desc_ = "";
      /**
       * <code>optional string desc = 11;</code>
       */
      public boolean hasDesc() {
        return ((bitField0_ & 0x00000400) == 0x00000400);
      }
      /**
       * <code>optional string desc = 11;</code>
       */
      public java.lang.String getDesc() {
        java.lang.Object ref = desc_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            desc_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string desc = 11;</code>
       */
      public com.google.protobuf.ByteString
          getDescBytes() {
        java.lang.Object ref = desc_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          desc_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string desc = 11;</code>
       */
      public Builder setDesc(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000400;
        desc_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string desc = 11;</code>
       */
      public Builder clearDesc() {
        bitField0_ = (bitField0_ & ~0x00000400);
        desc_ = getDefaultInstance().getDesc();
        onChanged();
        return this;
      }
      /**
       * <code>optional string desc = 11;</code>
       */
      public Builder setDescBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000400;
        desc_ = value;
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:SimpleObject)
    }

    // @@protoc_insertion_point(class_scope:SimpleObject)
    private static final com.keyhunter.test.serialization.proto.Simple.SimpleObject DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.keyhunter.test.serialization.proto.Simple.SimpleObject();
    }

    public static com.keyhunter.test.serialization.proto.Simple.SimpleObject getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    @java.lang.Deprecated public static final com.google.protobuf.Parser<SimpleObject>
        PARSER = new com.google.protobuf.AbstractParser<SimpleObject>() {
      public SimpleObject parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new SimpleObject(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<SimpleObject> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<SimpleObject> getParserForType() {
      return PARSER;
    }

    public com.keyhunter.test.serialization.proto.Simple.SimpleObject getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_SimpleObject_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_SimpleObject_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\033src/main/proto/Simple.Proto\"\265\001\n\014Simple" +
      "Object\022\014\n\004name\030\001 \001(\t\022\r\n\005value\030\002 \001(\t\022\013\n\003a" +
      "ge\030\003 \001(\005\022\014\n\004mail\030\004 \001(\t\022\r\n\005score\030\005 \001(\001\022\016\n" +
      "\006height\030\006 \001(\001\022\016\n\006weight\030\007 \001(\001\022\016\n\006school\030" +
      "\010 \001(\t\022\017\n\007teacher\030\t \001(\t\022\017\n\007parents\030\n \003(\t\022" +
      "\014\n\004desc\030\013 \001(\tB0\n&com.keyhunter.test.seri" +
      "alization.protoB\006Simple"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_SimpleObject_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_SimpleObject_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_SimpleObject_descriptor,
        new java.lang.String[] { "Name", "Value", "Age", "Mail", "Score", "Height", "Weight", "School", "Teacher", "Parents", "Desc", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
